// <auto-generated />
namespace FantasyIsland.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RequiredvirtualGenreofDestinationCommentedoutAdminandGuest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RequiredvirtualGenreofDestinationCommentedoutAdminandGuest));
        
        string IMigrationMetadata.Id
        {
            get { return "202011130112291_Required virtual Genre of Destination. Commented out Admin and Guest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
